### ISSUE TITLE
Module breaks dynamic blocks with "invalid parameters: attributes"

### ISSUE THREAD

**Issue by BrechtVds** [newfold-labs/wp-module-patterns#27]
Copying [this issue](https://github.com/bluehost/bluehost-wordpress-plugin/issues/759) I'm having with the Bluehost plugin here, since the problem seems to be originating from this module.

**Summarize the issue (briefly)**
The latest 3.4.2 version of the Bluehost plugin breaks dynamic blocks, apparently caused by the 0.1.6 version of wp-module-patterns.

**Steps to reproduce**
1. Activate the Blue Host plugin
2. Add the default "Latest Comments" block in the Block Editor

Set up on example site with only the Bluehost plugin activated:
1. Login through magic link: https://app.instawp.io/wordpress-auto-login?site=$2y$10$ZxAE1euu2UWDsIMZc8tmGeTbaObQhlN/xPbrkCg9kGSI.ymi.8//6
2. Check out sample post with "Latest Comments" block: https://depressed-deer-inalc.instawp.xyz/wp-admin/post.php?post=1&action=edit

**Expected behavior**
The latest comments show up. Instead, you get a "Error loading block: Invalid parameter(s): attributes" error message. This is the full error:
`{"code":"rest_invalid_param","message":"Invalid parameter(s): attributes","data":{"status":400,"params":{"attributes":"nfdGroupDivider is not a valid property of Object."},"details":{"attributes":{"code":"rest_additional_properties_forbidden","message":"nfdGroupDivider is not a valid property of Object.","data":null}}}}`

**Browser (with version) & Operating System (with version)**
  * Browser: Safari 16.6
  * Operating System: MacOS 13.5
  * Device: Mac Mini

**Additional context**
As far as I can tell **all** dynamic blocks are broken. It came on my radar because it breaks the recipe block of my WP Recipe Maker plugin. Several customers have contacted me about this issue, so it would be great if this could get resolved soon. Thanks!

**Comment by brankoconjic** [comment]
Thanks for reporting this. We've identified the issue and the fix will be included in the next release (planned for tomorrow).
